name: Astro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Astro check (opzionale)
        run: npm run check
        continue-on-error: true  # Se vuoi che fallisca solo se necessario

      - name: Build Astro site
        run: npm run build --if-present

      - name: Run tests
        run: npm test
